name: Hello WorkFlow


# Mention what events trigger the WorkFlow for the Pipeline

on:
  push: 
    branches: ["main"]

jobs:
# Mention the job named as "greet"
  greet:
    runs-on: ubuntu-latest

    steps:
      - name: checkout your repository for any code
        uses: actions/checkout@v4
    
      - name: Print a greeting message
        run: echo "Hello from the GitHub actions!"

      - name: Print date 
        run : echo "the date is :" $(date)
